name: Build Only

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
      env:
        update: true


    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs --no-dev --optimize-autoloader

    - name: Add vendor
      run: |
        rm -rf .gitignore
        git config --global user.email "i@yrc.me"
        git config --global user.name "yrccondor"
        git add .
        git commit -m "Add vendor"

    - name: Create zip package
      run: git archive --format=zip --output "${{ github.workspace }}/${{ github.event.repository.name }}.zip" HEAD

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
        if-no-files-found: error
