name: Build Only

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
      env:
        update: true


    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs --no-dev --optimize-autoloader

    - name: Prepare build files
      run: |
        rm -rf .gitignore
        rm -rf README
        rm -rf README.md
        rm -rf gutenberg-src
        rm -rf composer.json
        rm -rf composer.lock
        rm -rf changelog.txt

    - name: Upload build artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.workspace }}
        if-no-files-found: error
